export type Category = "logical" | "verbal" | "spatial" | "memory" | "analytical" | "social";

export interface Question {
	category: Category;
	type: "choice" | "memory" | "scale";
	prompt: string;
	promptEn: string;
	options: string[];
	optionsEn: string[];
	correctIndex?: number; // for choice type
	study?: string; // for memory type
	studyEn?: string; // for memory type
	studySeconds?: number; // for memory type
}

export const CATEGORY_META: Record<Category, { label: string; labelEn: string; emoji: string; color: string; desc: string; descEn: string; }> = {
	logical: { label: "المنطق والرياضيات", labelEn: "Logic & Math", emoji: "🧮", color: "#4A90E2", desc: "القدرة على التحليل وحل المشكلات الرياضية.", descEn: "Ability to analyze and solve mathematical problems." },
	verbal: { label: "اللغة والكلمات", labelEn: "Language & Words", emoji: "✍️", color: "#50E3C2", desc: "إتقان اللغة والتعبير بوضوح.", descEn: "Mastery of language and clear expression." },
	spatial: { label: "التصور المكاني", labelEn: "Spatial Awareness", emoji: "🗺️", color: "#F5A623", desc: "فهم العلاقات بين الأشكال والمساحات.", descEn: "Understanding relationships between shapes and spaces." },
	memory: { label: "الذاكرة والتركيز", labelEn: "Memory & Focus", emoji: "🧠", color: "#BD10E0", desc: "القدرة على تذكر المعلومات والتركيز.", descEn: "Ability to recall information and maintain focus." },
	analytical: { label: "التحليل وحل المشكلات", labelEn: "Analysis & Problem-Solving", emoji: "🔍", color: "#9013FE", desc: "تفكيك المشاكل المعقدة وإيجاد حلول.", descEn: "Breaking down complex problems and finding solutions." },
	social: { label: "الذكاء الاجتماعي", labelEn: "Social Intelligence", emoji: "❤️", color: "#D0021B", desc: "فهم مشاعر الآخرين والتفاعل معهم بفعالية.", descEn: "Understanding others' feelings and interacting effectively." },
};

export const MI_QUESTIONS: Question[] = [
  // ----------------- 1. الذكاء المنطقي-الرياضي (9 أسئلة) -----------------
  {
		category: "logical",
		type: "choice",
		prompt: "ما هو الرقم التالي في المتسلسلة: 2, 4, 8, 16, ...؟",
		promptEn: "What is the next number in the sequence: 2, 4, 8, 16, ...?",
		options: ["24", "32", "64"],
		optionsEn: ["24", "32", "64"],
		correctIndex: 1,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "إذا كان سعر مضرب وكرة هو 1.10 دولار، وسعر المضرب يزيد عن سعر الكرة بدولار واحد، فكم سعر الكرة؟",
		promptEn: "A bat and a ball cost $1.10 in total. The bat costs $1.00 more than the ball. How much does the ball cost?",
		options: ["0.10 دولار", "0.05 دولار", "1.00 دولار"],
		optionsEn: ["$0.10", "$0.05", "$1.00"],
		correctIndex: 1,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "ما هو الرقم التالي في المتسلسلة: 1, 4, 9, 16, 25, ...؟",
		promptEn: "What is the next number in the sequence: 1, 4, 9, 16, 25, ...?",
		options: ["36", "49", "30"],
		optionsEn: ["36", "49", "30"],
		correctIndex: 0,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "إذا كان كل الـ (أ) هم (ب)، وبعض الـ (ب) هم (ج)، فهل بعض الـ (أ) هم (ج) بالضرورة؟",
		promptEn: "If all A are B, and some B are C, are some A necessarily C?",
		options: ["نعم", "لا", "لا يمكن التحديد"],
		optionsEn: ["Yes", "No", "Cannot be determined"],
		correctIndex: 1,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "أي الأشكال التالية يكمل النمط: ●, ▲, ■, ●, ▲, ...؟",
		promptEn: "Which of the following shapes completes the pattern: ●, ▲, ■, ●, ▲, ...?",
		options: ["●", "▲", "■"],
		optionsEn: ["●", "▲", "■"],
		correctIndex: 2,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "ما هو الرقم الذي لا ينتمي للمجموعة: 2, 3, 5, 7, 9, 11؟",
		promptEn: "Which number does not belong in the set: 2, 3, 5, 7, 9, 11?",
		options: ["3", "7", "9"],
		optionsEn: ["3", "7", "9"],
		correctIndex: 2, // 9 is not a prime number
  },
  {
		category: "logical",
		type: "choice",
		prompt: "لديك 5 آلات تنتج 5 قطع في 5 دقائق. كم دقيقة تحتاج 100 آلة لإنتاج 100 قطعة؟",
		promptEn: "It takes 5 machines 5 minutes to make 5 widgets. How long would it take 100 machines to make 100 widgets?",
		options: ["100 دقيقة", "50 دقيقة", "5 دقائق"],
		optionsEn: ["100 minutes", "50 minutes", "5 minutes"],
		correctIndex: 2,
  },
  {
		category: "logical",
		type: "choice",
		prompt: "ما هو الحرف التالي في المتسلسلة: أ, ج, هـ, ز, ...؟",
		promptEn: "What is the next letter in the sequence: A, C, E, G, ...?",
		options: ["ح", "ط", "ك"],
		optionsEn: ["H", "I", "K"],
		correctIndex: 1,
  },
  {
		category: "logical",
		type: "scale",
		prompt: "أستمتع بحل الألغاز المنطقية وألعاب السودوكو.",
		promptEn: "I enjoy solving logic puzzles and Sudoku.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // ----------------- 2. الذكاء اللغوي (9 أسئلة) -----------------
  {
		category: "verbal",
		type: "choice",
		prompt: "أي كلمة هي الأنسب لوصف شخص يتحدث كثيرًا؟",
		promptEn: "Which word best describes someone who talks a lot?",
		options: ["صامت", "متحفظ", "ثرثار"],
		optionsEn: ["Silent", "Reserved", "Talkative"],
		correctIndex: 2,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "ما هو عكس كلمة 'شجاع'؟",
		promptEn: "What is the opposite of 'brave'?",
		options: ["قوي", "سريع", "جبان"],
		optionsEn: ["Strong", "Fast", "Cowardly"],
		correctIndex: 2,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "أكمل المثل: 'الطبيب للمستشفى مثل المعلم للـ...'",
		promptEn: "Complete the analogy: 'Doctor is to Hospital as Teacher is to...'",
		options: ["كتاب", "مدرسة", "طالب"],
		optionsEn: ["Book", "School", "Student"],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "أي كلمة لا تنتمي للمجموعة: تفاحة، موزة، جزرة، برتقالة؟",
		promptEn: "Which word does not belong: Apple, Banana, Carrot, Orange?",
		options: ["موزة", "برتقالة", "جزرة"],
		optionsEn: ["Banana", "Orange", "Carrot"],
		correctIndex: 2,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "ما معنى كلمة 'عابر' أو 'زائل'؟",
		promptEn: "What is a synonym for 'ephemeral' or 'transient'?",
		options: ["دائم", "مؤقت", "قوي"],
		optionsEn: ["Permanent", "Temporary", "Strong"],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "أكمل الجملة: 'على الرغم من المطر، ___ الذهاب في نزهة.'",
		promptEn: "Complete the sentence: 'Despite the rain, he ___ to go for a walk.'",
		options: ["رفض", "قرر", "نسي"],
		optionsEn: ["refused", "decided", "forgot"],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "ما هو جمع كلمة 'مكتبة'؟",
		promptEn: "What is the plural of 'library'?",
		options: ["مكاتب", "مكتبات", "كتب"],
		optionsEn: ["Desks", "Libraries", "Books"],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "أي جملة هي الأصح نحوياً؟",
		promptEn: "Which sentence is grammatically correct?",
		options: ["ذهبوا الأولاد إلى الحديقة.", "الأولاد ذهبوا إلى الحديقة.", "إلى الحديقة ذهبوا الأولاد."],
		optionsEn: ["The boys they went to the park.", "The boys went to the park.", "To the park the boys went."],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "scale",
		prompt: "أستمتع بقراءة الكتب والمقالات، وأجد سهولة في تعلم كلمات جديدة.",
		promptEn: "I enjoy reading books and articles, and I find it easy to learn new words.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // ----------------- 3. الذكاء المكاني (9 أسئلة) -----------------
  {
		category: "spatial",
		type: "choice",
		prompt: "إذا قمت بتدوير مكعب 90 درجة إلى اليمين، فما هو الوجه الذي سيصبح في الأعلى؟",
		promptEn: "If you rotate a cube 90 degrees to the right, which face will be on top?",
		options: ["الوجه الأمامي", "الوجه الخلفي", "لا يمكن تحديده"],
		optionsEn: ["Front face", "Back face", "Cannot be determined"],
		correctIndex: 3,
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "أي من الأشكال التالية هو صورة معكوسة (مرآة) للشكل الأصلي؟",
		promptEn: "Which of the following shapes is a mirror image of the original?",
		options: ["نفس الشكل", "شكل مقلوب", "شكل معكوس"],
		optionsEn: ["The same shape", "An upside-down shape", "A reversed shape"],
		correctIndex: 2,
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "إذا كنت تواجه الشمال ثم استدرت 180 درجة، فأي اتجاه ستواجه؟",
		promptEn: "If you are facing North and turn 180 degrees, which direction will you be facing?",
		options: ["شرق", "غرب", "جنوب"],
		optionsEn: ["East", "West", "South"],
		correctIndex: 2,
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "أي قطعة تكمل اللغز (البازل)؟",
		promptEn: "Which piece completes the puzzle?",
		options: ["قطعة ذات حافة مستقيمة", "قطعة زاوية", "قطعة وسطية"],
		optionsEn: ["A piece with a straight edge", "A corner piece", "A middle piece"],
		correctIndex: 1, // Example
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "كم عدد المكعبات الصغيرة في هذا الشكل الكبير؟ (يظهر شكل 3x3x3)",
		promptEn: "How many small cubes are in this large cube? (A 3x3x3 cube is shown)",
		options: ["9", "18", "27"],
		optionsEn: ["9", "18", "27"],
		correctIndex: 2,
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "إذا طويت هذه الشبكة، أي شكل ثلاثي الأبعاد ستحصل عليه؟ (تظهر شبكة مكعب)",
		promptEn: "If you fold this net, which 3D shape will you get? (A cube net is shown)",
		options: ["هرم", "مكعب", "اسطوانة"],
		optionsEn: ["Pyramid", "Cube", "Cylinder"],
		correctIndex: 1,
  },
  {
		category: "spatial",
		type: "choice",
		prompt: "أي من هذه المسارات هو الأقصر بين النقطتين أ و ب؟",
		promptEn: "Which of these paths is the shortest between point A and point B?",
		options: ["مسار متعرج", "خط مستقيم", "قوس كبير"],
		optionsEn: ["A winding path", "A straight line", "A large arc"],
		correctIndex: 1,
  },
  {
		category: "spatial",
		type: "scale",
		prompt: "أجد من السهل قراءة الخرائط وتجميع الأثاث من الكتيبات.",
		promptEn: "I find it easy to read maps and assemble furniture from instructions.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "spatial",
		type: "scale",
		prompt: "لدي قدرة جيدة على تخيل الأشياء في ثلاثة أبعاد.",
		promptEn: "I have a good ability to visualize things in three dimensions.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // ----------------- 4. الذاكرة والتركيز (9 أسئلة) -----------------
  {
		category: "memory",
		type: "memory",
		prompt: "ادرس القائمة التالية جيدًا.",
		promptEn: "Study the following list carefully.",
		study: "تفاحة - قطار - قمر",
		studyEn: "Apple - Train - Moon",
		studySeconds: 5,
		options: ["شمس - سيارة - برتقالة", "تفاحة - قطار - قمر", "نجمة - طائرة - موزة"],
		optionsEn: ["Sun - Car - Orange", "Apple - Train - Moon", "Star - Plane - Banana"],
		correctIndex: 1,
  },
  {
		category: "memory",
		type: "memory",
		prompt: "احفظ هذا الرقم.",
		promptEn: "Memorize this number.",
		study: "8642",
		studyEn: "8642",
		studySeconds: 4,
		options: ["8462", "8624", "8642"],
		optionsEn: ["8462", "8624", "8642"],
		correctIndex: 2,
  },
  {
		category: "memory",
		type: "memory",
		prompt: "ادرس ترتيب الأشكال.",
		promptEn: "Study the order of the shapes.",
		study: "■ ▲ ●",
		studyEn: "■ ▲ ●",
		studySeconds: 4,
		options: ["▲ ■ ●", "■ ● ▲", "■ ▲ ●"],
		optionsEn: ["▲ ■ ●", "■ ● ▲", "■ ▲ ●"],
		correctIndex: 2,
  },
  {
		category: "memory",
		type: "memory",
		prompt: "احفظ هذه الكلمات.",
		promptEn: "Memorize these words.",
		study: "بيت - شجرة - بحر",
		studyEn: "House - Tree - Sea",
		studySeconds: 5,
		options: ["بيت - نهر - شجرة", "بيت - شجرة - بحر", "بحر - بيت - سماء"],
		optionsEn: ["House - River - Tree", "House - Tree - Sea", "Sea - House - Sky"],
		correctIndex: 1,
  },
  {
		category: "memory",
		type: "memory",
		prompt: "احفظ هذا النمط من الحروف.",
		promptEn: "Memorize this letter pattern.",
		study: "A-B-C-D",
		studyEn: "A-B-C-D",
		studySeconds: 4,
		options: ["A-C-B-D", "A-B-D-C", "A-B-C-D"],
		optionsEn: ["A-C-B-D", "A-B-D-C", "A-B-C-D"],
		correctIndex: 2,
  },
  {
		category: "memory",
		type: "memory",
		prompt: "ادرس الألوان التالية جيدًا.",
		promptEn: "Study the following colors carefully.",
		study: "أحمر - أزرق - أخضر",
		studyEn: "Red - Blue - Green",
		studySeconds: 4,
		options: ["أحمر - أصفر - أخضر", "أحمر - أزرق - برتقالي", "أحمر - أزرق - أخضر"],
		optionsEn: ["Red - Yellow - Green", "Red - Blue - Orange", "Red - Blue - Green"],
		correctIndex: 2,
  },
  {
		category: "memory",
		type: "scale",
		prompt: "أتذكر بسهولة أعياد ميلاد أصدقائي وأفراد عائلتي.",
		promptEn: "I easily remember the birthdays of my friends and family.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "memory",
		type: "scale",
		prompt: "يمكنني التركيز على مهمة واحدة لفترة طويلة دون تشتت.",
		promptEn: "I can focus on a single task for a long time without getting distracted.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "memory",
		type: "scale",
		prompt: "أنا جيد في تذكر الأسماء والوجوه.",
		promptEn: "I am good at remembering names and faces.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // ----------------- 5. الذكاء التحليلي (9 أسئلة) -----------------
  {
		category: "analytical",
		type: "choice",
		prompt: "كل القطط تحب السمك. (أ) صحيح، (ب) خاطئ. إذا كانت هذه الفرضية صحيحة، و'مشمش' قط، فماذا نستنتج؟",
		promptEn: "All cats like fish. (A) True, (B) False. If this premise is true, and 'Mishmish' is a cat, what can we conclude?",
		options: ["مشمش لا يحب السمك", "مشمش يحب السمك", "لا يمكننا معرفة"],
		optionsEn: ["Mishmish doesn't like fish", "Mishmish likes fish", "We cannot know"],
		correctIndex: 1,
  },
  {
		category: "analytical",
		type: "choice",
		prompt: "طائر يطير دائمًا نحو الجنوب. في أي اتجاه يكون منقاره؟",
		promptEn: "A bird always flies south. In which direction is its beak pointing?",
		options: ["شمال", "جنوب", "شرق"],
		optionsEn: ["North", "South", "East"],
		correctIndex: 1,
  },
  {
		category: "analytical",
		type: "choice",
		prompt: "إذا كان المطر يسبب بلل الشوارع، والشارع الآن مبتل، فهل هذا يعني أنه أمطر بالتأكيد؟",
		promptEn: "If rain makes streets wet, and the street is now wet, does it mean it definitely rained?",
		options: ["نعم، بالتأكيد", "لا، ليس بالضرورة", "مستحيل"],
		optionsEn: ["Yes, definitely", "No, not necessarily", "Impossible"],
		correctIndex: 1,
  },
  {
		category: "analytical",
		type: "choice",
		prompt: "ما هو الافتراض الأساسي في جملة 'يجب أن تدرس بجد لتنجح'؟",
		promptEn: "What is the underlying assumption in the sentence 'You must study hard to succeed'?",
		options: ["النجاح مستحيل", "الدراسة بجد تؤدي للنجاح", "الجميع يدرس بجد"],
		optionsEn: ["Success is impossible", "Studying hard leads to success", "Everyone studies hard"],
		correctIndex: 1,
  },
  {
		category: "analytical",
		type: "choice",
		prompt: "سيارة تسير بسرعة ثابتة. إذا قطعت 100 كم في ساعتين، فكم ستقطع في 3 ساعات؟",
		promptEn: "A car is traveling at a constant speed. If it travels 100 km in 2 hours, how far will it travel in 3 hours?",
		options: ["150 كم", "200 كم", "300 كم"],
		optionsEn: ["150 km", "200 km", "300 km"],
		correctIndex: 0,
  },
  {
		category: "analytical",
		type: "scale",
		prompt: "عندما أواجه مشكلة معقدة، أحب تفكيكها إلى أجزاء أصغر.",
		promptEn: "When faced with a complex problem, I like to break it down into smaller parts.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "analytical",
		type: "scale",
		prompt: "أبحث دائمًا عن الأنماط والعلاقات بين الأشياء.",
		promptEn: "I often look for patterns and relationships between things.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "analytical",
		type: "scale",
		prompt: "أفضل اتخاذ القرارات بناءً على الأدلة والمنطق بدلاً من المشاعر.",
		promptEn: "I prefer to make decisions based on evidence and logic rather than feelings.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  {
		category: "analytical",
		type: "scale",
		prompt: "أستمتع بتنظيم المعلومات في جداول أو قوائم.",
		promptEn: "I enjoy organizing information into charts or lists.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // ----------------- 6. الذكاء الاجتماعي (9 أسئلة) -----------------
  {
		category: "social",
		type: "scale",
		prompt: "أجد من السهل فهم ما يشعر به أصدقائي حتى لو لم يتكلموا.",
		promptEn: "I find it easy to understand what my friends are feeling even if they don't speak.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
  // =================================================
  // أضف بقية الأسئلة هنا. هذه 6 أمثلة إضافية.
  // =================================================
  {
		category: "logical",
		type: "choice",
		prompt: "إذا كان اليوم هو الأربعاء، فما هو اليوم الذي يأتي بعد 3 أيام من الغد؟",
		promptEn: "If today is Wednesday, what day is it 3 days after tomorrow?",
		options: ["السبت", "الأحد", "الاثنين", "الثلاثاء"],
		optionsEn: ["Saturday", "Sunday", "Monday", "Tuesday"],
		correctIndex: 1,
  },
  {
		category: "verbal",
		type: "choice",
		prompt: "ما هو عكس كلمة 'شجاع'؟",
		promptEn: "What is the opposite of 'brave'?",
		options: ["قوي", "سريع", "جبان", "ذكي"],
		optionsEn: ["Strong", "Fast", "Cowardly", "Smart"],
		correctIndex: 2,
  },
    {
		category: "spatial",
		type: "choice",
		prompt: "أي من الأشكال التالية لا ينتمي للمجموعة؟ (مربع، دائرة، مثلث، خط مستقيم)",
		promptEn: "Which of the following shapes does not belong? (Square, Circle, Triangle, Straight Line)",
		options: ["مربع", "دائرة", "مثلث", "خط مستقيم"],
		optionsEn: ["Square", "Circle", "Triangle", "Straight Line"],
		correctIndex: 3, // الخط ليس شكلاً مغلقاً
  },
  {
		category: "memory",
		type: "memory",
		prompt: "ادرس الألوان التالية جيدًا.",
		promptEn: "Study the following colors carefully.",
		study: "أحمر - أزرق - أخضر",
		studyEn: "Red - Blue - Green",
		studySeconds: 4,
		options: ["أحمر - أصفر - أخضر", "أحمر - أزرق - برتقالي", "أحمر - أزرق - أخضر"],
		optionsEn: ["Red - Yellow - Green", "Red - Blue - Orange", "Red - Blue - Green"],
		correctIndex: 2,
  },
    {
		category: "analytical",
		type: "choice",
		prompt: "طائر يطير دائمًا نحو الجنوب. في أي اتجاه يكون منقاره؟",
		promptEn: "A bird always flies south. In which direction is its beak pointing?",
		options: ["شمال", "جنوب", "شرق", "غرب"],
		optionsEn: ["North", "South", "East", "West"],
		correctIndex: 1,
  },
    {
		category: "social",
		type: "scale",
		prompt: "أستمتع بالعمل ضمن فريق أكثر من العمل بمفردي.",
		promptEn: "I enjoy working in a team more than working alone.",
		options: ["لا أوافق بشدة", "لا أوافق", "محايد", "أوافق", "أوافق بشدة"],
		optionsEn: ["Strongly Disagree", "Disagree", "Neutral", "Agree", "Strongly Agree"],
  },
];